### ISSUE TITLE
OOM and Process Hang on Windows 10 in LanguageServerWrapperTest

### ISSUE THREAD

**Issue by sebthom** [eclipse/lsp4e#1103]
As of PR https://github.com/eclipse/lsp4e/pull/1044 (@ava-fred) running integration tests reproducible results in a OOMs and process hangs on at least Windows 10. I tried with different JDKs - same effect. Reverting the commit from https://github.com/eclipse/lsp4e/pull/1044 solves the issue.

The issue appears when the LanguageServerWrapperTest.testStopAndActivate() is executed.

Running `mvn verify -Dtest=LanguageServerWrapperTest#testStopAndActivate` immediately results in OOM within a few seconds and process hangs.

I am attaching a thread dump where one can see that thousands of threads are created.
[threaddump-1725956087712.txt](https://github.com/user-attachments/files/16941993/threaddump-1725956087712.txt)

Because of the LSPs async natures I am having difficulties tracking down the root cause.

Can anyone else reproduce that issue? @rubenporras @mickaelistria

Even though this only appears in that one integration test so prominently it probably has an underlying cause that may affect end-users during normal usage.

**Comment by ava-fred** [comment]
I finally managed to reproduce the OOM exception on my Windows 10 machine, but I had to change the test to make it run longer. I guess my Windows 10 machine is much better at counting to 10_000_000 than yours :->.

As you mentioned, it is hard to track what is going on because of the async nature of things, but I'll see what I can find.

**Comment by sebthom** [comment]
I switched to a Ryzen CPU some time ago. Maybe they behave somewhat different making the underlying issue more prominently visible.

**Comment by rubenporras** [comment]
Hi @sebthom , thanks for looking at this. Since @ava-fred is looking into it, I will not look into this problem myself (Note: in case you did not notice from our activity in the project, we both work for the same company).

Regards

**Comment by sebthom** [comment]
This issue now also affects most of the Jenkins builds see https://ci.eclipse.org/lsp4e/job/lsp4e-github/job/main/75/console

**Comment by ava-fred** [comment]
My analysis shows that LanguageServerWrapperTest.testStopAndActivate() leaks threads executing ConcurrentMessageProcessor.run() because the thread started in MockConnectionProviderMultiRootFolders.start() is never shut down. This was so before #1044, the only thing that apparently changed with this PR is that the balance between the 2 loops in the test has changed slightly so that the thread leak now causes actual problems.  
I have been working on fixing the test, but I have also struggled with the asynchronicity of LSP4E. On reflection, I am not sure if fixing the test is worthwhile. I don't see what it actually tests and in what scenario it would fail (as opposed to crashing because it runs out of resources). The comments in the test are not helpful: the PR mentioned in the Javadoc was abandoned, and I don't see how LanguageServerWrapper.isActive() would ever throw, synchronisation or not.
@rubenporras , do you think the test should be kept and fixed or should it be removed?

**Comment by rubenporras** [comment]
Hi @ava-fred , 

I see that the test was added as part of https://github.com/eclipse/lsp4e/pull/691. It is true that it can be seen by simple code inspection than `isActive` and `start` are both synchronized, but on the other hand, it is preventing a race condition that happened before, so it could happen again if we make a mistake.

Do I understand correctly that the problem is that wrapper.stop(); does not wait for the process in the background to be finished, and then by calling `wrapper.stop()`/`wrapper.start()` in a loop, we just potentially create many threads?

I wonder if we can fix the test by waiting after `wrapper.stop()`; for the processing inside the future to be really finished before calling `wrapper.start()`; Would something as simple as adding a manual sleep in the test work? If so I think we could also call something after `wrapper.stop()` and before `wrapper.start()` that uses the future `LanguageServerWrapper#initializeFuture`, like `LanguageServerWrapper#getServerCapabilities`. What do you think of that?

**Comment by rubenporras** [comment]
I think we can go the rout of waiting a bit. I will not stress test any race conditions as much as now, but I think it would be a good compromise.

**Comment by ava-fred** [comment]
I think I know why the test is still crashing even when I fix the `MockConnectionProviderMultiRootFolders` shutdown. I also think I know how to fix the problem in `LanguageServerWrapper` which causes the crash. I discussed this with @rubenporras  offline and we agreed that we would like to keep the test in principle, but I will change it so that it becomes more useful for detecting such problems.

**Comment by sebthom** [comment]
I can confirm that the test works now. Thanks!
