### ISSUE TITLE
Customizable icons/labels for SymbolKind depending on the content-type

### ISSUE THREAD

**Issue by gerdleon** [eclipse/lsp4e#252]
Hi,

as the owner of a product based on Eclipse that implements support for several custom DSLs I would like to customize the icon and label for the SymbolKind.

I understand that LSP only supports a defined set of SymbolKinds. Extending this list for every possible SymbolKind does not sound useful.

What could be done in the client: adapt the symbols/labels based on the content type. 

Not all of the default symbols (and labels for them) make sense to the user. For example:
A DSL that describes a table can be mapped to:
* table -> struct (or class?)
* column -> field (or property?)

What do you think?

**Comment by mickaelistria** [comment]
I don't think it's a viable approach to make it custom according to content-type; it adds a lot of complexity and try to bypass the responsibility and goals of LSP. I see you reported it to https://github.com/Microsoft/language-server-protocol/issues/344 , lets wait for it to happen.

**Comment by gerdleon** [comment]
What do you think about customizing the icons independent of the content-type?
It would be nice to be able to adapt the UI in the packaged products. The symbols carry a meaning which is not necessarily fitting the business domain.

**Comment by mickaelistria** [comment]
I think customization of things that should be standardized in LSP is actually a bad thing as it make people place effort in the customized stuff instead of placing effort in the standard stuff; which will create more value.
Eclipse Platform is aiming at providing support for icon themes; if it does, then one can use it for LSP4E as well; but I don't think LSP4E is the right place for such UI customization stuff.
Looking at your user story, you did the right thing by requesting field&column to the LSP spec, that is the best approach and LSP4E will highly welcome support for thos symbolkinds once they're spec'd.

**Comment by gerdleon** [comment]
Agreed, icon themes would the correct approach. I will watch https://github.com/eclipse-platform/eclipse.platform.ui/issues/13
