### ISSUE TITLE
DSPLaunch hangs when used with Dart Debug Adapter

### ISSUE THREAD

**Issue by sebthom** [eclipse/lsp4e#262]
I am trying to integrate the dart debug adapter with lsp4j/lsp4e, however after the first view messages the communication hangs and I have no idea why. I doubt that it's LSP4E, but a more underlying problem, so I opened the issue here.

This is the communication trace:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "clientID": "lsp4e.debug",
    "adapterID": "adapterId",
    "linesStartAt1": true,
    "columnsStartAt1": true,
    "pathFormat": "path",
    "supportsVariableType": true,
    "supportsVariablePaging": true,
    "supportsRunInTerminalRequest": true
  }
}
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "supportsConfigurationDoneRequest": true,
    "supportsConditionalBreakpoints": true,
    "supportsEvaluateForHovers": true,
    "exceptionBreakpointFilters": [
      {
        "filter": "All",
        "label": "All Exceptions",
        "default": false
      },
      {
        "filter": "Unhandled",
        "label": "Uncaught Exceptions",
        "default": true
      }
    ],
    "supportsRestartRequest": false,
    "supportsDelayedStackTraceLoading": true,
    "supportsLogPoints": true,
    "supportsTerminateRequest": true,
    "supportsClipboardContext": true
  }
}
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "launch",
  "params": {
    "args": [],
    "cwd": "D:\\workspaces\\projects\\dart-hotreloader",
    "vmAdditionalArgs": [],
    "program": "D:\\workspaces\\projects\\dart-hotreloader\\lib\\main.dart",
    "noDebug": false
  }
}
{
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": null
}
```

That is what I see in the UI:
![image](https://user-images.githubusercontent.com/426959/197042438-e9a5095b-1ddf-4944-bd10-6b959bff2eaa.png)

The Debug Adapter can be launched manually using the command `dart debug_adapter`. This is how I launch it:
```java
var debuggerOpts = new TreeBuilder<String>() 
   .put("cwd", workdir.toString())
   .put("program", dartMainFilePath.toString())
   .put("args", programArgs)
   .put("vmAdditionalArgs", vmArgs)
   .getMap();

try {
   var builder = new DSPLaunchDelegateLaunchBuilder(config, ILaunchManager.DEBUG_MODE, launch, monitor);
   builder.setLaunchDebugAdapter(dartSDK.getDartExecutable().toString(), List.of("debug_adapter"));
   builder.setMonitorDebugAdapter(config.getAttribute(DSPPlugin.ATTR_DSP_MONITOR_DEBUG_ADAPTER, true));
   builder.setDspParameters(debuggerOpts);
   new LaunchDebugConfig().launch(builder);
} catch (final CoreException ex) {
   Dialogs.showStatus("Failed to start debug session", Dart4EPlugin.status().createError(ex), true);
}
```

This is the documentation for the Dart DAP support https://github.com/dart-lang/sdk/blob/main/pkg/dds/tool/dap/README.md

Any thoughts/ideas are very much appreciated.

**Comment by jonahgraham** [comment]
The issue here is in LSP4E and I have transferred to LSP4E repo. 

A while ago an attempt at fixing an NPE fundamentally changed the behaviour of the debug client. When the client receives the `initialized` event it must start sending out the breakpoints, followed by (if supported) the configuration done. The entire startup is then supposed to be marked complete when both the `configurationDone` response is received and the `launch` request response is received. 

The current code:

https://github.com/eclipse/lsp4e/blob/e17be24d13c6729b44e85cc8b73efde5c0514332/org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java#L254

is waiting for:

- `future` which is the Future for the `launch/attach` response
- `initialized` which is the Future for the `initialized` event

Then once _both_ of those are received, it is sending the breakpoints followed by the `configurationDone` request:

https://github.com/eclipse/lsp4e/blob/e17be24d13c6729b44e85cc8b73efde5c0514332/org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java#L254-L269

However the client needs to start sending breakpoints once `initialized` is received. The debug adapter can send `initialized` event anytime after the `initialize` request and _may_ not send a response to `launch/attach` request until as late as after `configurationDone` response.

The picture in https://github.com/microsoft/vscode/issues/4902#issuecomment-368583522 is a better picture showing the parallel nature of the debug client when talking to the adapter than [this pic](https://microsoft.github.io/debug-adapter-protocol/img/init-launch.png) in the [DAP spec](https://microsoft.github.io/debug-adapter-protocol/overview)

Unfortunately #66 moved a bracket around to address an NPE, but that wasn't the correct fix. Reverting #66 makes the dart debug adapter work properly again. However that reintroduces the potential NPE. For that I will open another issue as it requires its own long discussion.

**Comment by sebthom** [comment]
@mickaelistria Now that this got fixed. I would be very interested in getting a new LSP4E release that includes this patch as well as #256. WDYT, how soon would that be possible?

**Comment by mickaelistria** [comment]
Let's wait for #265 before considering a release.

**Comment by jonahgraham** [comment]
> Let's wait for #265 before considering a release.

It is now merged.
