### ISSUE TITLE
[Feature Request]: "Language Server Processes" view

### ISSUE THREAD

**Issue by sebthom** [eclipse/lsp4e#518]
I'd like to suggest an Eclipse view that shows all spawned language server processes, showing language server name, initial project, pid, command line and a button to terminate a language server.

Sometimes language servers start misbehaving and only restarting them helps. This means either closing all editor windows and waiting for X seconds, or restarting eclipse, or manually killing the respective processes in the task manager.

**Comment by mickaelistria** [comment]
Why a view? OSs generally provide the feature of listing processes and children processes very well and a user who can know whether/why/which language server to kill should usually be able to identify the process.

**Comment by sebthom** [comment]
> Why a view? OSs generally provide the feature of listing processes and children processes very well and a user who can know whether/why/which language server to kill should usually be able to identify the process.

I sometimes see half a dozen node.exe processes in the task manager and have no idea which one to kill.

**Comment by sebthom** [comment]
My personal intention is general Eclipse users.

**Comment by sebthom** [comment]
But I now also find it very convenient while troubleshooting a language server.

**Comment by martinlippert** [comment]
From my point of view, this view should not be visible by default in any of the usual perspectives and the user should not see this if everything just goes well.

But if something goes wrong or behaves in a strange way, I would find such a view quite useful in order to get an idea about all the associated and running language server processes. For that purpose (troubleshooting) I would find it even useful to enhance this view with a few additional actions, like the ability to see/jump to the log output of the language server process (might require some work behind the scenes to have a homogenous way to get the log output), stop the process (maybe to get it restarted), see the consumed memory, or even more.

In general, all this information can already be found somewhere else (using `jps`, other command line tools), but such a view would make it a lot easier to troubleshoot issues when users report issues, I think.

**Comment by sebthom** [comment]
> From my point of view, this view should not be visible by default in any of the usual perspectives and the user should not see this if everything just goes well.
 
Definitely, this view needs to be manually opened.

> For that purpose (troubleshooting) I would find it even useful to enhance this view with a few additional actions, like the ability to see/jump to the log output of the language server process (might require some work behind the scenes to have a homogenous way to get the log output), stop the process (maybe to get it restarted), see the consumed memory, or even more.

I implemented stopping of processes in #519. This is actually the main reason I would like to have such a view.
I also wondered about displaying memory consumption but I don't really really know how to get this metric from external processes in a portable way.
