### ISSUE TITLE
Code Actions / Quickfix: Quickfix deactivated in Problems view

### ISSUE THREAD

**Issue by bastiandoetsch** [eclipse/lsp4e#616]
Hi, 

maybe the code actions are not transferred from the language server correctly or a flag is missing (`isPreferred`?). So, this may not even be a LSP4e shortcoming.

**Problem:**
In the Problems view quickfix is always deactivated when opening the context menu:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/20150761/233549142-b9db6507-8115-4321-9ab6-e7eebff513ed.png">

When pressing CMD+1 it appears though:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/20150761/233549086-b4518d8e-1af1-4e03-9a50-e38a0bc70514.png">

Is this expected? When is the quickfix menu option enabled in Problems view?

**Comment by martinlippert** [comment]
Maybe @BoykoAlex can shed some light on this or look into this. At least he made quick fixes appear in the problems view in the Spring Tools, so there must be a way.

**Comment by BoykoAlex** [comment]
@bastiandoetsch Indeed this works fine in Spring Tools, but i don't recall doing anything special for the quick fix to show up in the problems view...
I recall quick fixes are created in response to "Code Action" request... A few things to keep in mind therefore:
1. Code Action type being returned back. I'd ensure it is the "Quickfix" type
2. The request has context. The request coming in from the editor would have a problem diagnostic object as the context if invoked as quick fix. Otherwise it would have selected range - I'd check what kind of requests you get. You'd be getting both. I suspect you. might only be expecting one kind of "Code Action" request

**Comment by bastiandoetsch** [comment]
Thanks, I'll investigate some further :)

**Comment by mickaelistria** [comment]
Are there steps to reproduce the issue with one of the publicly available LS integrations (eg Corrosion, Wild Web Developer, eclipseide-jdtls...)?

**Comment by mickaelistria** [comment]
Or if you can write a test case using the mock language server that is used in LSP4E tests, that would help a lot as well.

**Comment by bastiandoetsch** [comment]
I don't use them, but to answer the question, Snyk Language Server is publicly available (https://github.com/snyk/snyk-ls). One needs to register a free account though.

**Comment by bastiandoetsch** [comment]
This seems to work now :)
